apiVersion: v1
kind: Namespace
metadata:
  name: guestbook-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-guestbook
  namespace: guestbook-app
  labels:
    app: guestbook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: app
        image: asia-southeast1-docker.pkg.dev/pythonproject-502117/guestbook-repo/gcp-guestbook:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
          name: http
        
        # Environment variables (Updated dynamically after Cloud SQL is created)
        env:
        - name: DB_HOST
          value: "127.0.0.1"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "postgres"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db-password

        resources:
          requests:
            memory: "256Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "500m"

        livenessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 15
          periodSeconds: 15

        readinessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 10
          periodSeconds: 10

      # 2. The Cloud SQL Auth Proxy Sidecar Container
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.0
        args:
          - "--port=5432"
          - "pythonproject-502117:asia-southeast1:guestbook-db-instance"
        resources:
          requests:
            memory: "128Mi"
            cpu: "10m"
          limits:
            memory: "256Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: gke-guestbook-svc
  namespace: guestbook-app
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  ports:
  - port: 80
    targetPort: 8501
    protocol: TCP
    name: http
  selector:
    app: guestbook
