# SonarQube Project Configuration
sonar.projectKey=gcp-guestbook
sonar.projectName=GCP Cloud Guestbook
sonar.projectVersion=1.0

# Path to source code
sonar.sources=.
sonar.exclusions=venv/**,.github/**,jenkins-setup/**,terraform/**

# Encoding
sonar.sourceEncoding=UTF-8
sonar.language=py
